### PR TITLE
zsv playground

### LINKED ISSUE #161: `zsv-playground` (https://github.com/iamazeem/zsv-playground)
I've been working on https://github.com/iamazeem/zsv-playground lately.
Most of the issues I reported here are the observations during its development.
LMK what you think. Would love to hear your feedback. Thanks!

### PR DESCRIPTION
**Pull request by iamazeem**
- [x] Separate job for wasm build
- [x] Separate job for deploying wasm build to GitHub Pages
- [x] Fix compiler warnings
- [x] Fix test coloring issue (replace `echo -e` with `printf`)
- [x] Ignore generated files
- [ ] <strike>Add support for `stdin`</strike>
  - not feasible to handle generically both for csv input and command line prompting
- [x] Add support for adding files
- [x] Test
  - With multiple browsers e.g. chrome, firefox, etc.
  - Make sure the cache is disabled during testing to avoid any surprises and/or side effects later
- [x] Update README

Other misc updates:

- Use `NO_THREADING` to skip `-pthread` flag
- Use `NO_STDIN` to disable stdin input for consistency
- Introduce `NO_PLAYGROUND` CLI flag for conditional switching of flags and main function name for playground and the rest

Resolves #161

TODOs:

- Verify deployment after merge to `main`
- Fix issues if any

Signed-off-by: Azeem Sajid <azeem.sajid@gmail.com>

### CODE REVIEW

**Comment by iamazeem** [comment]
@liquidaty: 
Going for a terminal style playground.
It seems more natural for a CLI app and there'll be no learning curve.

Here's an initial preview of the playground in the browser:

zsv-playground-demo-1

For an initial release, I'm going for the basic functionality only.
Please do share your feedback on this.
Any specific features that you've in mind that should be in the initial release?

**Comment by iamazeem** [comment]
@liquidaty: 
Going for a terminal style playground.
It seems more natural for a CLI app and there'll be no learning curve.

Here's an initial preview of the playground in the browser:

zsv-playground-demo-2

Targeting the basic functionality for an initial release.
Please do share your feedback on this.
Any specific features that should be in the initial release?

**Comment by iamazeem** [comment]
New demo:

zsv-playground-demo-3

**Comment by liquidaty** [comment]
Sounds good. Is it possible to run `sheet` in the playground? I am guessing it is not possible, but if it was, that would be very cool. I have seen a wasm build for ncurses, but have no idea whether there is any way to make it work on a web page.

**Comment by iamazeem** [comment]
@liquidaty:
> Is it possible to run `sheet` in the playground? I am guessing it is not possible, but if it was, that would be very cool.

Initially, I started looking for something that could enable `sheet` as well but found nothing promising.
Most of the examples were using a client/server model using SSH to display n/curses TUIs.

> I have seen a wasm build for ncurses, but have no idea whether there is any way to make it work on a web page.

Is this the one?
https://github.com/jamesbiv/ncurses-emscripten

**Comment by liquidaty** [comment]
@iamazeem this is great! Just two suggestions for now:
- add "rm" command-- this can simply be an alias for "zsv rm"
- add some sort of filename autocomplete when "tab" is entered. This does not have to be sophisticated; the main thing here is to make it easy to enter a file name into the command line, without having to exactly remember what the file name was

**Comment by liquidaty** [comment]
Two more!
- add a "save" command to download a file
- add a "wipe" command (maybe there is a better name for it?) to wipe out all saved data. Maybe also offer to do this when the web page is unloaded?

**Comment by iamazeem** [comment]
@liquidaty: Please review and test on your side.
The TAB autocompletion has also been implemented for zsv commands and flags.

Workflow run: https://github.com/liquidaty/zsv/actions/runs/12056785696
GitHub Pages artifact: https://github.com/liquidaty/zsv/actions/runs/12056785696/artifacts/2246338901

Demo:

zsv-playground-demo-6

**Comment by iamazeem** [comment]
@liquidaty: Online playground is live now: https://liquidaty.github.io/zsv/ :tada: :tada: :tada:

**Comment by iamazeem** [comment]
`test-sheet-3` is failing on find (`f`) command for any search string with sigsev 11 (invalid memory access).
https://github.com/liquidaty/zsv/actions/runs/12062759876/job/33636928077#step:5:1239

**Pull request merged**
