### PR TITLE
Close open files on caller side

### PR DESCRIPTION
**Pull request by iamazeem**
- Referece: #307
  - Need to close files to flush data
- Fix favicon for playground
- Exit `test-sheet-1` session properly
- Fix `test-sheet-12` intermittent failures
  - Add delay before capturing output
  - Update expected output accordingly

Signed-off-by: Azeem Sajid <azeem.sajid@gmail.com>

### CODE REVIEW

**Comment by iamazeem** [comment]
@liquidaty: Please review and merge. Thanks!

**Comment by liquidaty** [comment]
@iamazeem thank you, this is helpful in pointing out all the current areas that need fixing and proposing a solution. The only reason we are not merging this right away is that we will likely pursue an alternate solution which would be for the writer options to have `output_filename` that could be used instead of `stream`, whereby in `zsv_writer_new()`, if `output_filename` is specified then `stream` would be opened there, in which case it would also be closed by `zsv_writer_delete()`.

**Comment by iamazeem** [comment]
@liquidaty: Makes sense. :+1: 
However, without it, the commands with missing `fclose` won't work in playground.
The flushing is not being done in this case.

Also, the above solution would work the same for commands such as `2json`, `2db`, etc. where the writing is not CSV format? :thinking: 
How is the non-CSV format going to be encapsulated?

IMO, it may be done incrementally i.e. merge this one first and then iterate with the new solution.

**Comment by liquidaty** [comment]
Superseded by https://github.com/liquidaty/zsv/pull/310

**Pull request closed without merging**
