### PR TITLE
[CI] musl build updates

### PR DESCRIPTION
**Pull request by iamazeem**
- Separate job for musl with `alpine:latest` container
- Cleanup of Makefiles and shell scripts

Signed-off-by: Azeem Sajid <azeem.sajid@gmail.com>

### CODE REVIEW

**Comment by liquidaty** [comment]
@iamazeem could you also double-check if these contemplated changes have any measurable impact on the performance benchmarks?

**Comment by iamazeem** [comment]
@liquidaty: Here are the results:

---

# Benchmarks (`WITHOUT_SIMD=true`)

- Timestamp UTC: `2024-11-02T07:23:57Z`

## Releases Used

- <https://github.com/liquidaty/zsv/releases/download/v0.3.9-alpha/zsv-0.3.9-alpha-amd64-linux-musl.tar.gz>
- <https://github.com/eBay/tsv-utils/releases/download/v2.2.0/tsv-utils-v2.2.0_linux-x86_64_ldc2.tar.gz>
- <https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz>

## Results

### count

```
1 | zsv : real 0.17 user 0.16 sys 0.00
2 | zsv : real 0.17 user 0.17 sys 0.00
3 | zsv : real 0.17 user 0.17 sys 0.00
4 | zsv : real 0.17 user 0.16 sys 0.01
5 | zsv : real 0.18 user 0.17 sys 0.00
6 | zsv : real 0.17 user 0.17 sys 0.00
1 | xsv : real 0.08 user 0.07 sys 0.01
2 | xsv : real 0.08 user 0.08 sys 0.00
3 | xsv : real 0.08 user 0.07 sys 0.01
4 | xsv : real 0.08 user 0.08 sys 0.00
5 | xsv : real 0.08 user 0.08 sys 0.00
6 | xsv : real 0.08 user 0.07 sys 0.01
1 | tsv : real 0.08 user 0.08 sys 0.00
2 | tsv : real 0.08 user 0.09 sys 0.00
3 | tsv : real 0.09 user 0.06 sys 0.02
4 | tsv : real 0.08 user 0.08 sys 0.00
5 | tsv : real 0.08 user 0.07 sys 0.01
6 | tsv : real 0.09 user 0.08 sys 0.00
```

### select

```
1 | zsv : real 0.39 user 0.36 sys 0.02
2 | zsv : real 0.42 user 0.41 sys 0.00
3 | zsv : real 0.39 user 0.39 sys 0.00
4 | zsv : real 0.39 user 0.37 sys 0.01
5 | zsv : real 0.39 user 0.39 sys 0.00
6 | zsv : real 0.38 user 0.38 sys 0.00
1 | xsv : real 0.36 user 0.36 sys 0.00
2 | xsv : real 0.36 user 0.35 sys 0.01
3 | xsv : real 0.36 user 0.35 sys 0.00
4 | xsv : real 0.36 user 0.35 sys 0.00
5 | xsv : real 0.36 user 0.36 sys 0.00
6 | xsv : real 0.36 user 0.34 sys 0.01
1 | tsv : real 0.11 user 0.10 sys 0.00
2 | tsv : real 0.11 user 0.10 sys 0.00
3 | tsv : real 0.11 user 0.10 sys 0.00
4 | tsv : real 0.11 user 0.10 sys 0.00
5 | tsv : real 0.11 user 0.10 sys 0.00
6 | tsv : real 0.11 user 0.08 sys 0.02
```

---

# Benchmarks (`WITHOUT_SIMD=false`)

- Timestamp UTC: `2024-11-02T07:52:20Z`

## Releases Used

- <https://github.com/liquidaty/zsv/releases/download/v0.3.9-alpha/zsv-0.3.9-alpha-amd64-linux-musl.tar.gz>
- <https://github.com/eBay/tsv-utils/releases/download/v2.2.0/tsv-utils-v2.2.0_linux-x86_64_ldc2.tar.gz>
- <https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz>

## Results

### count

```
1 | zsv : real 0.03 user 0.03 sys 0.00
2 | zsv : real 0.03 user 0.03 sys 0.00
3 | zsv : real 0.03 user 0.03 sys 0.00
4 | zsv : real 0.03 user 0.03 sys 0.00
5 | zsv : real 0.03 user 0.03 sys 0.00
6 | zsv : real 0.03 user 0.03 sys 0.00
1 | xsv : real 0.08 user 0.07 sys 0.00
2 | xsv : real 0.08 user 0.07 sys 0.01
3 | xsv : real 0.08 user 0.07 sys 0.00
4 | xsv : real 0.08 user 0.07 sys 0.00
5 | xsv : real 0.08 user 0.07 sys 0.01
6 | xsv : real 0.08 user 0.07 sys 0.00
1 | tsv : real 0.08 user 0.07 sys 0.00
2 | tsv : real 0.08 user 0.08 sys 0.00
3 | tsv : real 0.08 user 0.08 sys 0.00
4 | tsv : real 0.08 user 0.08 sys 0.00
5 | tsv : real 0.08 user 0.08 sys 0.00
6 | tsv : real 0.08 user 0.08 sys 0.00
```

### select

```
1 | zsv : real 0.25 user 0.23 sys 0.01
2 | zsv : real 0.25 user 0.25 sys 0.00
3 | zsv : real 0.25 user 0.24 sys 0.01
4 | zsv : real 0.25 user 0.25 sys 0.00
5 | zsv : real 0.25 user 0.25 sys 0.00
6 | zsv : real 0.25 user 0.24 sys 0.00
1 | xsv : real 0.36 user 0.35 sys 0.00
2 | xsv : real 0.37 user 0.35 sys 0.01
3 | xsv : real 0.37 user 0.36 sys 0.00
4 | xsv : real 0.36 user 0.34 sys 0.02
5 | xsv : real 0.36 user 0.34 sys 0.01
6 | xsv : real 0.37 user 0.36 sys 0.00
1 | tsv : real 0.11 user 0.10 sys 0.00
2 | tsv : real 0.11 user 0.10 sys 0.00
3 | tsv : real 0.11 user 0.10 sys 0.00
4 | tsv : real 0.11 user 0.11 sys 0.00
5 | tsv : real 0.11 user 0.10 sys 0.00
6 | tsv : real 0.11 user 0.10 sys 0.00
```

---

**Notes**

- `zsv` musl build **without SIMD** is from this workflow run (https://github.com/liquidaty/zsv/actions/runs/11633809775).
- `zsv` musl build **with SIMD** is from this workflow run (https://github.com/liquidaty/zsv/actions/runs/11641005858).
- For `tsv-utils`, the latest Linux build isn't available for its latest release (`v2.2.1`) . Using its previous release (`v2.2.0`) instead.

**Comment by iamazeem** [comment]
A binary built with SIMD instructions fails with "**illegal instruction**" error on platforms where those instructions aren't available.
We don't necessarily have to publish the non-SIMD release.
The `WITHOUT_SIMD` flag is just there to handle such scenarios whenever needed.

**Comment by liquidaty** [comment]
@iamazeem I'm not aware of any chips from 2018+ that do not have some sort of SIMD capabilities, so is it possible that WITHOUT_SIMD is using unnecessarily conservative assumptions, and the better solution would be to better tailor the build to properly discover and use the available SIMD instructions? Alternatively is there a limitation to the musl compiler's ability to generate correct SIMD instructions for varied platforms?

**Comment by liquidaty** [comment]
> A binary built with SIMD instructions fails with "illegal instruction" error on platforms where those instructions aren't available. We don't necessarily have to publish the non-SIMD release. The WITHOUT_SIMD flag is just there to handle such scenarios whenever needed.

Disregard my prior comment, as I did not closely read the above-- thank you, makes sense. Let's include the WITHOUT_SIMD for CI, but not actually publish it (at least for now) upon release. Thank you!

**Comment by liquidaty** [comment]
@iamazeem lmk if this is ready to go and I will merge

**Review by liquidaty — APPROVED** [review]

**Comment by iamazeem** [comment]
Benchmarks from the latest run on `main` after merge:
https://github.com/liquidaty/zsv/actions/runs/11697708382

**Pull request merged**
