### PR TITLE
[CI] Add benchmarks' enhancements

### PR DESCRIPTION
**Pull request by iamazeem**
- Use build artifacts from other workflow runs using the run ID (optional)
- Use the latest released build otherwise

Signed-off-by: Azeem Sajid <azeem.sajid@gmail.com>

### CODE REVIEW

**Comment by iamazeem** [comment]
Steps:
- Go to https://github.com/liquidaty/zsv/actions/workflows/benchmarks.yml.
- Click on <kbd>Run workflow</kbd> dropdown
- Paste the workflow run ID to use zsv builds from
  - Otherwise, the latest release will be used
- Click on <kbd>Run workflow</kbd> button

**Comment by liquidaty** [comment]
@iamazeem the musl builds still seem a little off for a couple reasons. First, it seems odd that zsv would not still outperform tsv in the select benchmark just like the other zsv builds. is there any theoretical explanation for that? Second, when we build on our musl-gcc (x86_64-linux-musl-gcc (GCC) 9.4.0), the binary size is much smaller (2511640 bytes in the last run) than what is being produces in the artifacts. Could you send or post the config.musl file that is being generated by the musl build's `./configure` run so that we can examine?

**Comment by iamazeem** [comment]
@liquidaty:

> First, it seems odd that zsv would not still outperform tsv in the select benchmark just like the other zsv builds. is there any theoretical explanation for that?

Not yet.
Need to look into that.
Could be due to differences in internal API implementation.

> Second, when we build on our musl-gcc (x86_64-linux-musl-gcc (GCC) 9.4.0), the binary size is much smaller (2511640 bytes in the last run) than what is being produces in the artifacts.

Regarding **2511640**, is that for the stripped binary?

Just downloaded [zsv-0.3.9-alpha-amd64-linux-musl.tar.gz](https://github.com/liquidaty/zsv/actions/runs/11697569729/artifacts/2150468678), stripped the binary and got **2416888**:

```shell
$ ls -l zsv
-rwxr-xr-x 1 azeem azeem 3411440 Nov  6 10:12 zsv
$ strip -s zsv
$ ls -l zsv
-rwxr-xr-x 1 azeem azeem 2416888 Nov  6 15:03 zsv
```

> Could you send or post the config.musl file that is being generated by the musl build's ./configure run so that we can examine?

Sure, I'll share it later today.

**Comment by iamazeem** [comment]
@liquidaty: Please see `config.mk` file here:
https://github.com/liquidaty/zsv/actions/runs/11702289131/attempts/1#summary-32590175922

We may continue this discussion there. Thanks!

**Pull request merged**
