### PR TITLE
Integrate CodeQL

### PR DESCRIPTION
**Pull request by iamazeem**
- Configure CodeQL
  - Source + Tests

Check its results on my fork under:
- Security (https://github.com/iamazeem/zsv/security)
- Code scanning (https://github.com/iamazeem/zsv/security/code-scanning)

Alerts' count:
- without tests: 15
- with tests: 20

Signed-off-by: Azeem Sajid <azeem.sajid@gmail.com>

### CODE REVIEW

**Comment by iamazeem** [comment]
@liquidaty: Hi, please review this PR.
LMK how CodeQL should be triggered.
Currently, it's configured to be run manually.

You may check the results on my fork under:
- Security (https://github.com/iamazeem/zsv/security)
- Code scanning (https://github.com/iamazeem/zsv/security/code-scanning)

Alerts' count:
- without tests: 15
- with tests: 20

Thanks!

**Comment by liquidaty** [comment]
Great! let's have it trigger manually for now and we can change that after alerts have been reviewed/cleared. Thank you!

**Comment by iamazeem** [comment]
@liquidaty: Please review and merge.
The redundant triggers have been removed.
Thanks!

**Comment by iamazeem** [comment]
@liquidaty: Configured Dependabot for GHA with https://github.com/liquidaty/zsv/pull/182/commits/3b4604e4e755e87a9daf4f95ddb679f07d38ec2b.
For any GHA version updates, it'll send alerts on weekly basis.

Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

**Comment by iamazeem** [comment]
@liquidaty: Please disable the default setup.
See https://docs.github.com/en/code-security/code-scanning/troubleshooting-sarif-uploads/default-setup-enabled.
Once done, CodeQL workflow should run successfully.

**Comment by iamazeem** [comment]
Fixed.
Workflow: https://github.com/liquidaty/zsv/actions/runs/10382083012
Results: https://github.com/liquidaty/zsv/security/code-scanning

**Pull request merged**
