### PR TITLE
Introduce more features to `overwrite` command

### PR DESCRIPTION
**Pull request by CobbCoding1**
Features:
- `remove` subcommand
- `bulk-add` subcommand
- `bulk-remove` subcommand
- `--old-value` flag
- `--force` flag

The remove command works as expected, you pass the position you want to remove, and it deletes it from the database.
The bulk-add and bulk-remove flags both work similarly, as laid out in the usage message.
`overwrite <dummy.csv> bulk-add <bulk.csv>`
It can have the columns: row, col, val, author, timestamp, and old value.
The old-value and force flags also work as expected.

Some stylistic changes are that I've restructured the program, so there's an outer struct `zsv_overwrite` which passes the `ctx`, `args`, and `overwrite` around the functions, to avoid clutter in the functions. It also contains necessary information for the `bulk` operations, such as keeping track of the index of the columns.

Finally, I've added tests for every feature added here and their functionality.

### CODE REVIEW

**Comment by liquidaty** [comment]
@CobbCoding1 thank you. Could you pls make further changes as follows?

1. Add test for these new features. For example, tests for insert should include at least one that fails due to an existing conflict, and one that overwrites an existing conflict using the --force flag
2. Add `remove --all` which will entirely remove all overwrites (and the related sqlite3 db file)
3. remove strdup_n and use zsv_memdup instead
4. for insert: instead of checking for an existing value as a separate operation, just use "INSERT" if no --force flag is provided (and make sure to initially run "PRAGMA foreign_keys = on"), and use "INSERT OR REPLACE" otherwise
5. bulk operations should be wrapped in a transaction (begin / commit)-- see 2db.c for an example-- and also should use the above INSERT/INSERT OR REPLACE approach, and so therefore will not require separate checking for data conflicts

**Comment by CobbCoding1** [comment]
Alright, I'll get right on that.

**Comment by CobbCoding1** [comment]
Not done yet, will finish the rest tomorrow.

**Comment by liquidaty** [comment]
@CobbCoding1 can the purpose that is served by zsv_overwrites_compare() instead be achieved via the sql statement, so that zsv_overwrites_compare can be omitted, the code can be more concise and only one SQL operation needs to be performed?

**Comment by CobbCoding1** [comment]
Sure, good idea.

**Comment by CobbCoding1** [comment]
OK, I think that's everything. Let me know if there's any more changes I should make.

**Pull request merged**
